# Precise per-code ai_commands fix for Round-02 batch 1 (Functionality rows 2-201).
# Q-LIT: inner grep/echo double-quoted pattern -> single quotes inside ssh.
# Redfish nested-ssh curl -> run curl on agent-host (R5).
# PMBus: placeholder echo -> real i2cget with ${PMBUS_BUS:?}/${PMBUS_ADDR:?}.
# Pure ASCII only in this script. Uses python-openpyxl.
import openpyxl, sys

XLSX='data/REVISED_commands_merged_with_raw.xlsx'
FIX={
# ---------- Q-LIT: simple grep pattern quote swap ----------
'Wistron-HW-00072-V003': r'''sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no $DUT_USER@$DUT_IP "lscpu 2>&1 | grep -iE 'socket|core|model name'; echo ---; ls /sys/devices/system/cpu 2>&1 | head; echo ---numa---; numactl -H 2>&1 | head 2>&1"''',
'Wistron-HW-00073-V002': r'''sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no $DUT_USER@$DUT_IP "lscpu 2>&1 | grep -iE 'model name|cpu mhz|max mhz|min mhz'; echo ---; cat /proc/cpuinfo | grep -iE 'cpu mhz|model name' | head 2>&1"''',
'Wistron-HW-00074-V002': r'''sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no $DUT_USER@$DUT_IP "lscpu 2>&1 | grep -iE 'cache' 2>&1"''',
'Wistron-HW-00075-V002': r'''sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no $DUT_USER@$DUT_IP "lscpu 2>&1 | grep -iE '^CPU\(s\)|core|socket|thread|model name' 2>&1"''',
'Wistron-HW-00094-V003': r'''sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no $DUT_USER@$DUT_IP "ip -o link 2>&1 | grep -vE 'lo:|docker|veth' 2>&1"''',
'Wistron-HW-00110-V002': r'''-- PCIe slot check (x16 on slot 1 to 10): agent can auto-dump the OS-side PCIe device+link info sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no $DUT_USER@$DUT_IP "lspci -vvv 2>&1 | grep -Ei 'LnkCap|LnkSta|Region' | head -n 80; echo '---devices---'; lspci 2>&1" ; the BIOS setup-menu and uEFI shell pci output are read by the operator.''',
'Wistron-HW-00116-V005': r'''# agent host: sample fan RPM now, apply a brief CPU load on the DUT, then re-sample
ipmitool -I lanplus -C 17 -H "$BMC_IP" -U "$BMC_USER" -P "$BMC_PASS" sdr list 2>&1 | grep -iE 'fan'
---load (DUT, 30s)---
sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no $DUT_USER@$DUT_IP "sudo stress-ng --cpu $(nproc) --timeout 30s 2>&1 & sleep 40"
---after (agent host)---
ipmitool -I lanplus -C 17 -H "$BMC_IP" -U "$BMC_USER" -P "$BMC_PASS" sdr list 2>&1 | grep -iE 'fan' ''',
'Wistron-HW-00127-V005': r'''-- after an operator connects a USB-3.0 storage device, agent copies a test file to/from it and checks speed (needs the mounted USB device path). Agent part: sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no $DUT_USER@$DUT_IP "lsusb 2>&1; echo ---dmesg---; dmesg | grep -iE 'usb [0-9]|new.*usb' | tail -20 2>&1"''',
'Wistron-HW-00128-V005': r'''-- repeated USB add/remove via the kernel is triggered by physical plug; agent reads `dmesg` USB enumeration after the operator hot-plugs. Agent part: sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no $DUT_USER@$DUT_IP "lsusb 2>&1; echo ---dmesg---; dmesg | grep -iE 'usb [0-9]|new.*usb' | tail -20 2>&1"''',
'Wistron-HW-00148-V003': r'''-- TPM detection: the agent reads the OS TPM detection sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no $DUT_USER@$DUT_IP "ls -l /dev/tpm0 2>&1; dmesg 2>&1 | grep -i 'tpm' | grep -i 'found\|2.0'; cat /sys/class/tpm/tpm0/tpm_version_major 2>&1" but the BIOS-side TPM presence is a Setup screen the user/KVM reads.''',
'Wistron-HW-00155-V004': r'''-- Security mode: change the ROT security mode. Agent can only read current state from OS sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no $DUT_USER@$DUT_IP "mokutil --sb-state 2>&1; dmesg 2>&1 | grep -iE 'rot|pfr|secure' | tail -n 20 2>&1"; the security-mode change requires the TPM physical-presence jumper/switch and BIOS F1 setup navigation by an operator.''',
'Wistron-HW-00158-V003': r'''sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no $DUT_USER@$DUT_IP "ls -l /dev/tpm0 /dev/tpmrm0 2>&1; echo ---tpm_sysfs---; ls -l /sys/class/tpm/tpm0 2>&1; echo ---tpm_cap---; command -v tpm2_getcap >/dev/null && tpm2_getcap -c properties-fixed 2>&1 | grep -iE 'version|TPM2' | head -4 || echo 'tpm2-tools not installed' 2>&1"''',
'Wistron-HW-00162-V002': r'''-- Install OS sheet-A (Secure Boot enabled): install Windows Server with Secure Boot/TPM on the SUT. Agent can pre-check the secure-boot state from OS sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no $DUT_USER@$DUT_IP "bootctl status 2>&1 | grep -iE 'secure boot|setup mode'; mokutil --sb-state 2>&1"; the OS install itself needs the Windows ISO + interactive setup (BIOS F1, RAID driver loading) performed by an operator.''',
'Wistron-HW-00184-V002': r'''-- Active NIC - dedicated (Dedicated): verify the Dedicated NIC link is up and reachable: agent checks sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no $DUT_USER@$DUT_IP "ip link 2>&1 | grep -iE 'link|state' | head; nmcli device status 2>&1 | head 2>&1" on the host-facing side and pings the BMC IP from the network; the BIOS "server mgmt" page IP check + web login are operator/BMC-UI reads.''',
'Wistron-HW-00189-V004': r'''-- Active NIC - shared (Shared - NC-SI): verify the Shared - NC-SI NIC link is up and reachable: agent checks sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no $DUT_USER@$DUT_IP "ip link 2>&1 | grep -iE 'link|state' | head; nmcli device status 2>&1 | head 2>&1" on the host-facing side and pings the BMC IP from the network; the BIOS "server mgmt" page IP check + web login are operator/BMC-UI reads.''',
# ---------- Redfish nested-ssh curl -> agent-host curl (R5) ----------
'Wistron-HW-00185-V002': r'''-- Set dedicated port as DHCP(IPv4) (Dedicated as DHCP IPv4): agent reads the BMC LAN source/address with ipmitool -I lanplus -C 17 -U "$BMC_USER" -P "$BMC_PASS" -H "$BMC_IP" lan print 1 2>&1 | grep -iE "IP Address|Subnet|DHCP|Source" (or Redfish EthernetInterface read via curl -s -k -u "$BMC_USER:$BMC_PASS" "https://$BMC_IP/redfish/v1/Managers/1/EthernetInterfaces" 2>&1); setting the DHCP mode itself is done in BMC/BIOS UI by the operator.''',
'Wistron-HW-00186-V002': r'''-- Set dedicated port as static(IPv4) (Dedicated as static IPv4): agent verifies the assigned static address with ipmitool -I lanplus -C 17 -U "$BMC_USER" -P "$BMC_PASS" -H "$BMC_IP" lan print 1 2>&1 | grep -iE "IP Address|Subnet|Gateway" (or Redfish EthernetInterface read via curl -s -k -u "$BMC_USER:$BMC_PASS" "https://$BMC_IP/redfish/v1/Managers/1/EthernetInterfaces/1" 2>&1); entering the static IP + web-login are operator/BMC-UI steps.''',
'Wistron-HW-00187-V002': r'''-- Set dedicated port as DHCP(IPv6) (Dedicated as DHCP IPv6): agent reads the BMC LAN source/address with ipmitool -I lanplus -C 17 -U "$BMC_USER" -P "$BMC_PASS" -H "$BMC_IP" lan print 1 2>&1 | grep -iE "IP Address|Subnet|DHCP|Source" (or Redfish EthernetInterface read via curl -s -k -u "$BMC_USER:$BMC_PASS" "https://$BMC_IP/redfish/v1/Managers/1/EthernetInterfaces" 2>&1); setting the DHCP mode itself is done in BMC/BIOS UI by the operator.''',
'Wistron-HW-00188-V002': r'''-- Set dedicated port as static(IPv6) (Dedicated as static IPv6): agent verifies the assigned static address with ipmitool -I lanplus -C 17 -U "$BMC_USER" -P "$BMC_PASS" -H "$BMC_IP" lan print 1 2>&1 | grep -iE "IP Address|Subnet|Gateway" (or Redfish EthernetInterface read via curl -s -k -u "$BMC_USER:$BMC_PASS" "https://$BMC_IP/redfish/v1/Managers/1/EthernetInterfaces/1" 2>&1); entering the static IP + web-login are operator/BMC-UI steps.''',
'Wistron-HW-00190-V003': r'''-- Set shared port as DHCP(IPv4) (Shared - NC-SI as DHCP IPv4): agent reads the BMC LAN source/address with ipmitool -I lanplus -C 17 -U "$BMC_USER" -P "$BMC_PASS" -H "$BMC_IP" lan print 1 2>&1 | grep -iE "IP Address|Subnet|DHCP|Source" (or Redfish EthernetInterface read via curl -s -k -u "$BMC_USER:$BMC_PASS" "https://$BMC_IP/redfish/v1/Managers/1/EthernetInterfaces" 2>&1); setting the DHCP mode itself is done in BMC/BIOS UI by the operator.''',
'Wistron-HW-00191-V004': r'''-- Set shared port as static(IPv4) (Shared - NC-SI as static IPv4): agent verifies the assigned static address with ipmitool -I lanplus -C 17 -U "$BMC_USER" -P "$BMC_PASS" -H "$BMC_IP" lan print 1 2>&1 | grep -iE "IP Address|Subnet|Gateway" (or Redfish EthernetInterface read via curl -s -k -u "$BMC_USER:$BMC_PASS" "https://$BMC_IP/redfish/v1/Managers/1/EthernetInterfaces/1" 2>&1); entering the static IP + web-login are operator/BMC-UI steps.''',
'Wistron-HW-00192-V003': r'''-- Set shared port as DHCP(IPv6) (Shared - NC-SI as DHCP IPv6): agent reads the BMC LAN source/address with ipmitool -I lanplus -C 17 -U "$BMC_USER" -P "$BMC_PASS" -H "$BMC_IP" lan print 1 2>&1 | grep -iE "IP Address|Subnet|DHCP|Source" (or Redfish EthernetInterface read via curl -s -k -u "$BMC_USER:$BMC_PASS" "https://$BMC_IP/redfish/v1/Managers/1/EthernetInterfaces" 2>&1); setting the DHCP mode itself is done in BMC/BIOS UI by the operator.''',
'Wistron-HW-00193-V003': r'''-- Set shared port as static(IPv6) (Shared - NC-SI as static IPv6): agent verifies the assigned static address with ipmitool -I lanplus -C 17 -U "$BMC_USER" -P "$BMC_PASS" -H "$BMC_IP" lan print 1 2>&1 | grep -iE "IP Address|Subnet|Gateway" (or Redfish EthernetInterface read via curl -s -k -u "$BMC_USER:$BMC_PASS" "https://$BMC_IP/redfish/v1/Managers/1/EthernetInterfaces/1" 2>&1); entering the static IP + web-login are operator/BMC-UI steps.''',
# ---------- Resolution xrandr grep quote swap ----------
'Wistron-HW-00196-V002': r'''-- Resolution change up - 1920x1200x16bit: change the Mini-DP video resolution/color depth up to 1920x1200@16bit in the OS display settings. Requires a person at the display + OS desktop GUI (Test -> Apply); agent can read the current mode with sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no $DUT_USER@$DUT_IP "xrandr 2>&1 | grep -iE 'connected|\*' | head 2>&1" if a GUI session is present, but the GUI change + visual confirmation are operator/visual.''',
'Wistron-HW-00197-V002': r'''-- Resolution change up - 2560 x 1440x16bit: change the Mini-DP video resolution/color depth up to 2560x1440@16bit in the OS display settings. Requires a person at the display + OS desktop GUI (Test -> Apply); agent can read the current mode with sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no $DUT_USER@$DUT_IP "xrandr 2>&1 | grep -iE 'connected|\*' | head 2>&1" if a GUI session is present, but the GUI change + visual confirmation are operator/visual.''',
'Wistron-HW-00198-V002': r'''-- Resolution change up - 3840 x 2160x16bit: change the Mini-DP video resolution/color depth up to 3840x2160@16bit in the OS display settings. Requires a person at the display + OS desktop GUI (Test -> Apply); agent can read the current mode with sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no $DUT_USER@$DUT_IP "xrandr 2>&1 | grep -iE 'connected|\*' | head 2>&1" if a GUI session is present, but the GUI change + visual confirmation are operator/visual.''',
'Wistron-HW-00199-V002': r'''-- Resolution change up - 4096 x 2160 x 16bit: change the Mini-DP video resolution/color depth up to 4096x2160@16bit in the OS display settings. Requires a person at the display + OS desktop GUI (Test -> Apply); agent can read the current mode with sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no $DUT_USER@$DUT_IP "xrandr 2>&1 | grep -iE 'connected|\*' | head 2>&1" if a GUI session is present, but the GUI change + visual confirmation are operator/visual.''',
'Wistron-HW-00201-V003': r'''-- Driver: check the VGA driver is loaded sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no $DUT_USER@$DUT_IP "lspci | grep -i -E 'VGA|display' 2>&1; sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no $DUT_USER@$DUT_IP "lsmod | grep -iE 'drm|nouveau|ast' 2>&1; dmesg | grep -i -E 'drm|VGA' | tail -n 15 2>&1" 2>&1".''',
'Wistron-HW-00210-V002': r'''-- Devcie detection: verify device detection in OS sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no $DUT_USER@$DUT_IP "lsusb 2>&1; ip link 2>&1 | grep -E '^[0-9]+:' | head 2>&1" with the device present; physical setup is operator-owned.  -- USB device-detection instance across all USB ports (OS view; BIOS view by operator).''',
# ---------- PMBus: replace placeholder with real i2cget (operator B) ----------
'Wistron-HW-00049-V004': r'''sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no "$DUT_USER@$DUT_IP"  "echo ---pmbus_names---; head -n 1 /sys/class/hwmon/hwmon*/name 2>/dev/null | grep -iE 'pmbus|psu|power' || echo no_pmbus_dev; echo ---i2c_buses---; sudo i2cdetect -l 2>/dev/null | grep -iE 'smbus|i2c' || echo no_i2c_tools; echo ---reg_CAPABILITY---; sudo i2cget -f -y ${PMBUS_BUS:?set PSU i2c bus (from i2cdetect above)} ${PMBUS_ADDR:?set PSU i2c addr (7-bit)} 0x19 2>&1"''',
'Wistron-HW-00050-V004': r'''sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no "$DUT_USER@$DUT_IP"  "echo ---pmbus_names---; head -n 1 /sys/class/hwmon/hwmon*/name 2>/dev/null | grep -iE 'pmbus|psu|power' || echo no_pmbus_dev; echo ---i2c_buses---; sudo i2cdetect -l 2>/dev/null | grep -iE 'smbus|i2c' || echo no_i2c_tools; echo ---reg_QUERY_MFR_SPECIFIC---; sudo i2cget -f -y ${PMBUS_BUS:?set PSU i2c bus} ${PMBUS_ADDR:?set PSU i2c addr} 0xE0 2>&1"''',
'Wistron-HW-00051-V005': r'''sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no "$DUT_USER@$DUT_IP"  "echo ---pmbus_names---; head -n 1 /sys/class/hwmon/hwmon*/name 2>/dev/null | grep -iE 'pmbus|psu|power' || echo no_pmbus_dev; echo ---i2c_buses---; sudo i2cdetect -l 2>/dev/null | grep -iE 'smbus|i2c' || echo no_i2c_tools; echo ---reg_PMBUS_REVISION---; sudo i2cget -f -y ${PMBUS_BUS:?set PSU i2c bus} ${PMBUS_ADDR:?set PSU i2c addr} 0x98 2>&1"''',
'Wistron-HW-00052-V005': r'''sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no "$DUT_USER@$DUT_IP"  "echo ---pmbus_names---; head -n 1 /sys/class/hwmon/hwmon*/name 2>/dev/null | grep -iE 'pmbus|psu|power' || echo no_pmbus_dev; echo ---i2c_buses---; sudo i2cdetect -l 2>/dev/null | grep -iE 'smbus|i2c' || echo no_i2c_tools; echo ---reg_MFR_TEMP1_MAX---; sudo i2cget -f -y ${PMBUS_BUS:?set PSU i2c bus} ${PMBUS_ADDR:?set PSU i2c addr} 0xB0 2>&1"''',
'Wistron-HW-00053-V004': r'''sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no "$DUT_USER@$DUT_IP"  "echo ---pmbus_names---; head -n 1 /sys/class/hwmon/hwmon*/name 2>/dev/null | grep -iE 'pmbus|psu|power' || echo no_pmbus_dev; echo ---i2c_buses---; sudo i2cdetect -l 2>/dev/null | grep -iE 'smbus|i2c' || echo no_i2c_tools; echo ---reg_MFR_TEMP2_MAX---; sudo i2cget -f -y ${PMBUS_BUS:?set PSU i2c bus} ${PMBUS_ADDR:?set PSU i2c addr} 0xB1 2>&1"''',
'Wistron-HW-00054-V004': r'''sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no "$DUT_USER@$DUT_IP"  "echo ---pmbus_names---; head -n 1 /sys/class/hwmon/hwmon*/name 2>/dev/null | grep -iE 'pmbus|psu|power' || echo no_pmbus_dev; echo ---i2c_buses---; sudo i2cdetect -l 2>/dev/null | grep -iE 'smbus|i2c' || echo no_i2c_tools; echo ---reg_MFR_IOUT_MAX---; sudo i2cget -f -y ${PMBUS_BUS:?set PSU i2c bus} ${PMBUS_ADDR:?set PSU i2c addr} 0xB5 2>&1"''',
'Wistron-HW-00055-V004': r'''sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no "$DUT_USER@$DUT_IP"  "echo ---pmbus_names---; head -n 1 /sys/class/hwmon/hwmon*/name 2>/dev/null | grep -iE 'pmbus|psu|power' || echo no_pmbus_dev; echo ---i2c_buses---; sudo i2cdetect -l 2>/dev/null | grep -iE 'smbus|i2c' || echo no_i2c_tools; echo ---reg_MFR_POUT_MAX---; sudo i2cget -f -y ${PMBUS_BUS:?set PSU i2c bus} ${PMBUS_ADDR:?set PSU i2c addr} 0xB6 2>&1"''',
'Wistron-HW-00056-V004': r'''sshpass -p "$DUT_PASS" ssh -o StrictHostKeyChecking=no "$DUT_USER@$DUT_IP"  "echo ---pmbus_names---; head -n 1 /sys/class/hwmon/hwmon*/name 2>/dev/null | grep -iE 'pmbus|psu|power' || echo no_pmbus_dev; echo ---i2c_buses---; sudo i2cdetect -l 2>/dev/null | grep -iE 'smbus|i2c' || echo no_i2c_tools; echo ---reg_APP_PROFILE_SUPPORT---; sudo i2cget -f -y ${PMBUS_BUS:?set PSU i2c bus} ${PMBUS_ADDR:?set PSU i2c addr} 0xEA 2>&1"''',
}

wb=openpyxl.load_workbook(XLSX)
changed=0; missing=[]
for sn in wb.sheetnames:
    ws=wb[sn]
    for r in ws.iter_rows(min_row=2):
        code=r[0].value
        if code is None: continue
        c=str(code).strip()
        if c in FIX:
            # safety: ai_can_execute must be PARTIAL (PMBus) as expected; Q-LIT keep original
            ws.cell(row=r[0].row, column=15, value=FIX[c])
            changed+=1
if missing: print('MISSING (not found):',missing)
print('changed',changed,'of',len(FIX))
if changed!=len(FIX):
    sys.exit('ERROR: not all codes updated')
wb.save(XLSX)
print('saved',XLSX)
